# This is a basic workflow to help you get started with Actions

name: Deploy Frontend

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  workflow_dispatch:

defaults:
  run:
    working-directory: front-end
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_dispatch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fetch master branch on runner
        uses: actions/checkout@v2
      
      - name: Build the app
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      
      - name: Stop the app
        uses: appleboy/ssh-action@master
        with:
          host: snf-880282.vm.okeanos.grnet.gr
          username: hardeng
          password: 12345
          script: ~/frontend/stop-frontend.sh
      
      - name: Send to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: "/home/runner/work/TL20-11/TL20-11/front-end/build"
          remote: "frontend/build"
          host: "snf-880282.vm.okeanos.grnet.gr"
          username: "hardeng"
          password: "12345"

      - name: Restart the app
        uses: appleboy/ssh-action@master
        with:
          host: snf-880282.vm.okeanos.grnet.gr
          username: hardeng
          password: 12345
          script: ~/frontend/start-frontend.sh
